name: build pipeline

on:
  push:
    branches:
      - main
      
env:
  IMAGE_TAG:  ${{ github.event.head_commit.message }}

jobs:

  build:
    name: Build-Publish-Docker-Image
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY  }}'
          
      - name: "Logging to Artifact registry"
        run: gcloud auth configure-docker asia-south2-docker.pkg.dev

      - name: Build the Docker image
        run: docker build -t asia-south2-docker.pkg.dev/test-dev-apps/test-repo/test:${{ env.IMAGE_TAG }} .
        
      - name: Push the docker images to Registry
        run: docker push asia-south2-docker.pkg.dev/test-dev-apps/test-repo/test:${{ env.IMAGE_TAG }}
